name: Calculate Total Minutes

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the calculation
        env:  # Transmettre le jeton ici
          authToken: ${{ secrets.GITHUB_TOKEN }}  # Utilise le jeton GitHub ou définissez votre propre token dans les secrets
        run: node calculateMinutes.js

    # Declare the output from this job
    outputs:
      grandTotalMinutes: ${{ steps.calculate.outputs.grandTotalMinutes }}

  build_on_github_actions:
    runs-on: ubuntu-latest
    needs: calculate
    if: ${{ needs.calculate.outputs.grandTotalMinutes < 2000.00 }}  # Correctly reference the output from the calculate job
    steps:
      - name: Build on GitHub Actions
        run: echo "Building on GitHub Actions runner"

  build_on_self_hosted:
    runs-on: self-hosted
    needs: calculate
    if: ${{ needs.calculate.outputs.grandTotalMinutes >= 2000.00 }}  # Correctly reference the output
    steps:
      - name: Build on self-hosted runner
        run: echo "Building on self-hosted runner"
