name: Calculate Total Minutes

on:
  push:
    branches:
      - main

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run the calculation
        id: calculate  # Add an ID to reference the job output
        run: node calculateMinutes.js

  build_on_github_actions:
    runs-on: ubuntu-latest
    needs: calculate
    if: ${{ steps.calculate.outputs.grandTotalMinutes < 2000.00 }}
    steps:
      - name: Build on GitHub Actions
        run: echo "Building on GitHub Actions runner"

  build_on_self_hosted:
    runs-on: self-hosted
    needs: calculate
    if: ${{ steps.calculate.outputs.grandTotalMinutes >= 2000.00 }}
    steps:
      - name: Build on self-hosted runner
        run: echo "Building on self-hosted runner"
