name: Calculate Total Minutes

on:
    push:
      branches:
        - main
        
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run the calculation
        run: node calculateMinutes.js

      - name: Print output
        if: ${{ env.GRAND_TOTAL_MINUTES > 2000.00 }}
        run: echo "hi"

      - name: Print output
        if: ${{ env.GRAND_TOTAL_MINUTES < 2000.00 }}
        run: echo "byby"
