name: Calculate Workflow Minutes

on:
  workflow_dispatch:

jobs:
  calculate_minutes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run script
        id: run_script
        run: |
          node script.js
        # Le script écrit maintenant la sortie dans output.json

      - name: Read total minutes from JSON
        id: read_output
        run: |
          TOTAL_MINUTES=$(jq '.grandTotalMinutes' output.json)
          echo "TOTAL_MINUTES=$TOTAL_MINUTES" >> $GITHUB_ENV

      - name: Display total minutes
        run: |
          echo "Total minutes used: ${{ env.TOTAL_MINUTES }}"

      