name: Calculate Workflow Minutes

on:
    push:
      branches:
        - main

jobs:
  calculate_minutes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run script
        id: run_script
        run: node test2.js

      - name: Display total minutes
        run: |
          echo "Total minutes used: ${{ steps.run_script.outputs.grandTotalMinutes }}"
